# Generated by Django 2.2.5 on 2019-09-30 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190929_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': (['due_back'],)},
        ),
    ]
